### ISSUE TITLE
[Enhancement]:  Add possibility to set logger output

### ISSUE THREAD

**Issue by rlsvr** [go-mojito/logger-zerolog#15]
### Description

I think it would be nice to use Output() functionality of zerolog to be able to log to file (too)

### Checklist:

- [X] I agree to follow Mojito's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests reports may be closed without explanation.

**Comment by 0SkillAllLuck** [comment]
This is a great idea, it might make sense to add this to the logger interface in mojito itself.

**Comment by 0SkillAllLuck** [comment]
PR to add functionality to mojito: [go-mojito/mojito#27](https://github.com/go-mojito/mojito/pull/27)
